[package]
name = "uts"
version = "0.1.0"
edition = "2021"
description = "Simple timestamp utility"
license = "MIT"
repository = "https://github.com/rustcrate/timestamp"
authors = ["Rust Crate<rustcrate@cloudxaas.com>"]

[dependencies]
